[package]
name = "iRockProgrammer"
version = "0.1.0"
edition = "2021"

[dependencies]
cursive = "0.21.1"
dotenvy_macro = "0.15.7"
octocrab = "0.44.1"
reqwest = { version = "0.12", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.140"
tokio = "1.44.1"
