name: Build and Release for iRock Mobile Programmer

on:
  pull_request:
    branches: [ main ]
    types: [ closed ]

jobs:
  build-and-release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-22.04-arm
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Extract version from Cargo.toml
        id: cargo_version
        run: |
          echo "version=$(grep '^version' Cargo.toml | head -1 | sed -E 's/version = \"([^\"]+)\"/\1/')" >> $GITHUB_OUTPUT

      - name: Install cargo-bundle
        run: cargo install cargo-bundle

      - name: Bundle App für Linux
        run: cargo bundle --release

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.cargo_version.outputs.version }}
          name: Release für iRock Mobile Programmer
          body: "Automatischer Build für iRock Mobile Programmer (aarch64)"
          files: |
            target/release/bundle/deb/iRockProgrammer_${{ steps.cargo_version.outputs.version }}_arm64.deb
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
