name: Build and Release for iRock Mobile Programmer

on:
  pull_request:
    branches: [ main ]
    types: [ closed ]

jobs:
  build-and-release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Installiere Cross-Compiler f端r aarch64
        run: sudo apt-get update && sudo apt-get install -y gcc-aarch64-linux-gnu aarch64-unknown-linux-gnu

      - name: Install Rust target
        run: rustup target add aarch64-unknown-linux-gnu aarch64-unknown-linux-musl

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Extract version from Cargo.toml
        id: cargo_version
        run: |
          echo "version=$(grep '^version' Cargo.toml | head -1 | sed -E 's/version = \"([^\"]+)\"/\1/')" >> $GITHUB_OUTPUT

      - name: Install cargo-bundle
        run: cargo install cargo-bundle

      - name: Bundle App f端r Linux 
        run: cargo bundle --release --target aarch64-unknown-linux-gnu --target-dir aarch64-unknown-linux-musl

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.cargo_version.outputs.version }}
          name: Release f端r iRock Mobile Programmer
          body: "Automatischer Build f端r iRock Mobile Programmer (aarch64)"
          files: |
            target/aarch64-unknown-linux-gnu/release/bundle/deb/iRockProgrammer_${{ steps.cargo_version.outputs.version }}_arm64.deb
            target/aarch64-unknown-linux-musl/release/bundle/deb/iRockProgrammer_${{ steps.cargo_version.outputs.version }}_arm64.deb
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
