name: Build and Release for iRock Mobile Programmer

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  build-and-release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract version from Cargo.toml
        id: cargo_version
        run: |
          VERSION=$(grep '^version =' Cargo.toml | head -n1 | cut -d '"' -f2)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install cross
        run: cargo install cross

      - name: Build for iRock Mobile Programmer (armv7)
        run: cross build --release --target=aarch64-unknown-linux-gnu

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.cargo_version.outputs.version }}
          name: Release für iRock Mobile Programmer
          body: 'Automatischer Build für iRock Mobile Programmer (armv7)'
          files: target/aarch64-unknown-linux-gnu/release/iRockProgrammer
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
