name: Build and Release for iRock Mobile Programmer

on:
  pull_request:
    branches: [ main ]
    types: [ closed ]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v4

      - name: Cache Cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-${{ hashFiles('**/Cargo.toml') }}

      - name: Extract version
        id: cargo_version
        run: |
          echo "version=$(cargo metadata --format-version=1 --no-deps \
            | jq -r '.packages[] | select(.name==\"iRockProgrammer\").version')" \
          >> $GITHUB_OUTPUT

      - name: Install deps on host
        run: |
          sudo apt-get update && sudo apt-get install -y jq docker.io
          cargo install --locked cargo-bundle

      - name: Cross‑Bundle via Docker
        run: |
          docker run --rm \
            -v "${{ github.workspace }}":/src -w /src \
            rustembedded/cross:aarch64-unknown-linux-gnu \
            cargo bundle --release --target aarch64-unknown-linux-gnu

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.cargo_version.outputs.version }}
          name: Release für iRock Mobile Programmer
          body: "Automatischer Build für iRock Mobile Programmer (aarch64)"
          files: target/aarch64-unknown-linux-gnu/release/bundle/iRockProgrammer.deb
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
