name: Build and Release for iRock Mobile Programmer

on:
  pull_request:
    branches: [ main ]
    types: [ closed ]

jobs:
  build:
    if: github.event.pull_request.merged == true
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04-arm
            label: linux-arm64
            bundle_path: target/release/bundle/deb/*.deb
          - os: macos-13
            label: macos
            bundle_path: target/release/bundle/osx/*.app
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install libudev-dev (nur Linux)
        if: startsWith(matrix.os, 'ubuntu')
        run: sudo apt-get update && sudo apt-get install -y libudev-dev

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/bin
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Extract version from Cargo.toml
        id: cargo_version
        run: |
          echo "version=$(grep '^version' Cargo.toml | head -1 | sed -E 's/version = \"([^\"]+)\"/\1/')" >> $GITHUB_OUTPUT

      - name: Install cargo-bundle
        run: cargo install cargo-bundle

      - name: Bundle App
        run: cargo bundle --release

      - name: Upload Bundle
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.label }}
          path: ${{ matrix.bundle_path }}

    outputs:
      version: ${{ steps.cargo_version.outputs.version }}

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: List all artifacts
        run: ls -R artifacts


      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ needs.build.outputs.version }}
          name: Release für iRock Mobile Programmer
          body: |
            Automatischer Build für iRock Mobile Programmer.
          files: artifacts/*/*
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
